### ISSUE TITLE
Wrong formatting for estimated proposal pass time

### ISSUE THREAD

**Issue by cuteolaf** [polkassembly/polkassembly#1046]
Link: https://polkadot.polkassembly.io/referenda/332
Screenshot:
![image](https://github.com/polkassembly/polkassembly/assets/53915161/b8e4640d-d27e-42b7-bb4a-91aa4acaf564)

**Comment by cuteolaf** [comment]
#1047

**Comment by KanishkaRajputd** [comment]
This issue has been resolved 

Thank you
