### ISSUE TITLE
URGENT: Images not being rendered

### ISSUE THREAD

**Issue by dudo50** [polkassembly/polkassembly#1272]
I edited my discussion few moments ago and now none images are being generated and formatting is gone.

In my editor they are present:
<img width="857" alt="Screenshot 2024-02-08 at 11 41 47" src="https://github.com/polkassembly/polkassembly/assets/55763425/ef63973a-25d3-43b4-b5d6-409ee0cab1c3">

Link of discussion:
https://kusama.polkassembly.io/post/2628

Please check this asap, our proposal goes live tomorrow and images are vital.

**Comment by dudo50** [comment]
This might be directly related to markdown fix commit you pushed into production 1 hour ago https://github.com/polkassembly/polkassembly/commit/51ba8bc9203a3181f5cb825da39a4175c91e5814

cc @jasmeets-6575 @KanishkaRajputd

**Comment by niklabh** [comment]
This is fixed.

**Comment by dudo50** [comment]
Thanks, @niklabh for being so prompt!

Happy to report, that indeed the issue is fixed now.
