### ISSUE TITLE
API Error: trackStatus Confirmed invalid

### ISSUE THREAD

**Issue by dcolley** [polkassembly/polkassembly#1345]
Attempting any API call where trackStatus != All fails

<img width="903" alt="image" src="https://github.com/polkassembly/polkassembly/assets/1845970/e9162769-752c-43cf-879b-f8e20184e177">

**Comment by KanishkaRajputd** [comment]
Hii @dcolley  
for any other status you just need to add another variable called proposalStatus which will an array on status
eg: ["Confirmed"]

Thank you
