### ISSUE TITLE
Wrong account balance with submitting with proxy

### ISSUE THREAD

**Issue by kianenigma** [polkassembly/polkassembly#1349]
When using proxy account, the button is disabled if the amount that I want to lock is more than the total balance of the proxy account, while it should be disabled if the amount that I want to lock is more than the total balance of the proxied account: 

<img width="545" alt="Screenshot 2024-02-27 at 10 31 46" src="https://github.com/polkassembly/polkassembly/assets/5588131/e18420a0-ad9a-48d2-8756-2b5e6381c7fe">

In this figure, if I want to vote with 1 DOT, the button works.

**Comment by KanishkaRajputd** [comment]
This issue has been resolved !
Thankyou

**Comment by LukeWheeldon** [comment]
It is not resolved for me @KanishkaRajputd
