### ISSUE TITLE
bug: unable to vote with account that has proxy set on it

### ISSUE THREAD

**Issue by hitchhooker** [polkassembly/polkassembly#1387]
![image](https://github.com/polkassembly/polkassembly/assets/15621959/1819285a-2724-43fc-b826-e82c1a41e713)
There is no way to vote without proxy now. 
even proxyvote is unticked UI tries to force usage of proxy account for voting.

**Comment by KanishkaRajputd** [comment]
It's fixed  @hitchhooker 
Thankyou

**Comment by hitchhooker** [comment]
Thank you @KanishkaRajputd for resolving it :-)
