### ISSUE TITLE
UI: in search result, going to next item doesn't reset the view to top.

### ISSUE THREAD

**Issue by thiolliere** [polkassembly/polkassembly#1398]
In this page

![Capture d’écran du 2024-03-08 10-10-23](https://github.com/polkassembly/polkassembly/assets/10416848/ff247b73-1fe8-4318-b850-b76b6089dd2d)

If I click to next page I get this view:

![Capture d’écran du 2024-03-08 10-13-14](https://github.com/polkassembly/polkassembly/assets/10416848/f1184983-6469-4622-a3d2-700e56ecacc5)

instead it should be this view

![Capture d’écran du 2024-03-08 10-10-40](https://github.com/polkassembly/polkassembly/assets/10416848/1da11566-f4d7-4816-ae38-f7741baada74)

So instead of showing me the last item of the new view, it should show the first item

**Comment by KanishkaRajputd** [comment]
Hii @thiolliere 
This issue has been resolved 
Thankyou
