### ISSUE TITLE
Remove unnecessary Twitter OAuth scopes

### ISSUE THREAD

**Issue by kdenhartog** [polkassembly/polkassembly#1410]
It looks like the Twitter verification request is requesting scopes that are not in use:

![image](https://github.com/polkassembly/polkassembly/assets/23125059/d34cd5b4-025c-49f8-b8a3-d9ac3cd5fc93)

I just took a look at the code and it's not needing any of these permissions. Looking at the API calls [made to twitter](https://github.com/search?q=repo%3Apolkassembly%2Fpolkassembly%20api.twitter.com&type=code) the only [GET call to /accounts/verify_credentials](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/manage-account-settings/api-reference/get-account-verify_credentials) requires user.read scope is all I believe.

Is there a reason that this is then requesting the additional scopes in the OAuth flow or can the majority of them be turned off?

**Comment by KanishkaRajputd** [comment]
Hii @kdenhartog 
It has been removed

Thank you
