### ISSUE TITLE
Raw password in payload of POST request when sign in

### ISSUE THREAD

**Issue by ltfschoen** [polkassembly/polkassembly#1504]
Even though the password gets sent via HTTPS isn't it a violation of Kerckhoff's Principle in that raw passwords are visible in the payload of POST requests when a user signs in via email? See below
https://polkadot-blockchain-academy.github.io/pba-book/cryptography/intro/page.html
![Screenshot_20240403-225205_Chrome](https://github.com/polkassembly/polkassembly/assets/6226175/902301ae-522e-4fcd-8d4f-238c6c901d6c)

**Comment by KanishkaRajputd** [comment]
Hii @ltfschoen 
Raw password in payload request is fine. It is secured by https ssl encryption.
 Only end user can see raw password.
 
 Thankyou
