### ISSUE TITLE
Comment replies not showing up

### ISSUE THREAD

**Issue by gautamdhameja** [polkassembly/polkassembly#1555]
Here is a potential bug scenario:
I have a treasury proposal and it is created via Polkadot JS portal referendum page and then the respective post is updated on both Subsquare and Polkassembly.

- User posts a comment on Subsquare. The comment also shows up on Polkassembly.
- Then the comment is replied via Polkassembly. This reply is showing up on Subsquare but not showing up on Polkassembly.
- Currently this scenario is reproducible in referendum 700, and comment - https://polkadot.polkassembly.io/referenda/700#662724f62a748388a6f6d6d1

**Comment by KanishkaRajputd** [comment]
The problem has been successfully resolved! Thank you for your cooperation!
