### ISSUE TITLE
Likes on posts not working

### ISSUE THREAD

**Issue by KarimJedda** [polkassembly/polkassembly#1599]
### Reproduction:

https://github.com/polkassembly/polkassembly/assets/5029053/2f889421-361d-4b2e-a0d2-3592a0a80457

### Notes: 

- The issue persists over longer periods of times / after clearing the cache 
- The issue persists when deactivating Adblock/uBlock
- Firefox 125.0 (64-bit)
- Tested on MacOS & Ubuntu

**Comment by niklabh** [comment]
looking into this

**Comment by KarimJedda** [comment]
Here's what I tried now: 

https://github.com/polkassembly/polkassembly/assets/5029053/80bdda49-0da1-4e96-94ff-e4b0c3f4c1d9

Logging out & Logging back in seemed to have fixed it. Thank you :hugs:
