### ISSUE TITLE
missing referendas on kusama with All filtering

### ISSUE THREAD

**Issue by hitchhooker** [polkassembly/polkassembly#1620]
![image](https://github.com/polkassembly/polkassembly/assets/15621959/262c0ede-1fcf-4e47-acdd-7db3d3015eaf)
https://kusama.polkassembly.io/all-posts?trackStatus=all&page=1 all posts in kusama missing more recent proposals after  395?
https://kusama.polkassembly.io/all-posts?trackStatus=submitted&page=1 submitted shows some of them?
https://kusama.polkassembly.io/all-posts?trackStatus=voting&page=1 also

**Comment by Szegoo** [comment]
This seems to be the case on Polkadot as well, with proposals after 795.

**Comment by hitchhooker** [comment]
this same issue seems to persist again. really annoying that all posts wont show all current referendas 

![image](https://github.com/user-attachments/assets/3357fb9b-793c-4141-bef6-cf02a0718372)
![image](https://github.com/user-attachments/assets/a8d3d345-3b23-40d8-a34a-6d90362a4ccd)


https://kusama.polkassembly.io/all-posts?trackStatus=all&page=1
