### ISSUE TITLE
notifications link faulty without id

### ISSUE THREAD

**Issue by hitchhooker** [polkassembly/polkassembly#1629]
![image](https://github.com/polkassembly/polkassembly/assets/15621959/5d57a402-4b3a-4a6f-9c1f-b2c320d2ed91)
notifications link faulty without id

**Comment by jasmeets-6575** [comment]
Hi,

The issue with the notification links missing the ID has been fixed. You should now see the correct URLs in your notifications.

Thanks to Notice for the assistance.

Best regards,
Polkassembly Team
