### ISSUE TITLE
fix markdown typography

### ISSUE THREAD

**Issue by hitchhooker** [polkassembly/polkassembly#1647]
![image](https://github.com/polkassembly/polkassembly/assets/15621959/eab3dcef-fc43-4efc-a7ed-cd1da17fa269)
![image](https://github.com/polkassembly/polkassembly/assets/15621959/5d4cebce-a458-4f8f-9ef2-e0fca1e69a49)

Markdown-rendered proposals often suffer from a "ransom note effect," making them hard to read. To improve readability and professionalism, could we work in CSS / typography of markdown or use something like [github-markdown-css](https://sindresorhus.com/github-markdown-css/)?

**Comment by Swapnil-Sagar** [comment]
Hi,

Thanks for the suggestion. We'll look into enhancing the CSS/typography for our markdown-rendered proposals to improve readability and avoid the "ransom note effect." Using something like github-markdown-css could be a good solution.

Appreciate your input!

Best,
Polkassembly Team

**Comment by hitchhooker** [comment]
typography seems to be way better now
