### ISSUE TITLE
Hex formatted display for identities not rendering as in polkadot.js

### ISSUE THREAD

**Issue by lobis** [polkassembly/polkassembly#1651]
My Kusama address `JKQKHRzJj9yWu8aAm7pAkWJBadhynXhyUxiwenvxUK5rsKW` has an identity registered through polkadot.js. In this identity the display name is a hex-formatted bytestring. This display name is correctly rendered in polkadot.js. In my case:

<img width="311" alt="image" src="https://github.com/polkassembly/polkassembly/assets/35803280/c653065a-45a4-489a-801f-343814096deb">

However on the polkassembly profile the display name is displayed as a hex-formatted string

- https://kusama.polkassembly.io/user/HoneyStake

<img width="986" alt="image" src="https://github.com/polkassembly/polkassembly/assets/35803280/5eab7a37-beec-40b1-9b7c-603142a1cca5">

I don't know if this is intentional but I would prefer if it would be displayed in the same way as in polkadot.js

Thanks!

**Comment by KanishkaRajputd** [comment]
This has been resolved 

Thanks
Polkassembly team
