### ISSUE TITLE
parachain 10000 error in the new multiasset proposal

### ISSUE THREAD

**Issue by niixonjavier** [polkassembly/polkassembly#1671]
In the new function to request USDT, USDC for proposals the parachain value is 10,000 and not 1,000 like in all proposal why? 
<img width="591" alt="Screenshot 2024-06-08 at 11 52 31 AM" src="https://github.com/polkassembly/polkassembly/assets/172148074/afec314d-942b-4612-8b58-f832d1e17ee7">
<img width="812" alt="Screenshot 2024-06-08 at 11 55 36 AM" src="https://github.com/polkassembly/polkassembly/assets/172148074/680de3cd-75ae-4b40-9b7e-d0fc1fe27e40">
<img width="1474" alt="Screenshot 2024-06-08 at 12 19 08 PM" src="https://github.com/polkassembly/polkassembly/assets/172148074/60965e0c-bc87-4c31-a7f7-c024b3f59c84">

**Comment by KanishkaRajputd** [comment]
![image](https://github.com/polkassembly/polkassembly/assets/97453078/e504088e-bfba-46c2-acb6-f2ab7f77a3e8)

This issue has been resolved.
You can verify it here.

Thank you,
Polkassembly Team
