### ISSUE TITLE
Issues with Environment Variables in .env File

### ISSUE THREAD

**Issue by AMIRKHANEF** [polkassembly/polkassembly#362]
I'm encountering an issue while working on the project. It seems to be a problem with environment variables and the configuration of the .env file.

1. Missing "NEXT_PUBLIC_DEFAULT_NETWORK" Environment Variable:
    I initially encountered an error indicating that the "NEXT_PUBLIC_DEFAULT_NETWORK" environment variable is missing.

```
   6 |  const defaultNetwork = process.env.NEXT_PUBLIC_DEFAULT_NETWORK;
   7 |  if (!defaultNetwork) {
>  8 |          throw Error('Please set "NEXT_PUBLIC_DEFAULT_NETWORK" environment variable');
     |               ^
   9 |  }
  10 |  return defaultNetwork;
  11 | })();
```

Thank you for your assistance in resolving these issues.

**Comment by niklabh** [comment]
NEXT_PUBLIC_DEFAULT_NETWORK=kusama can be used. You also would need firebase for running the project.

**Comment by Gaurav-Krishna-Gaali** [comment]
If you have set it up before @niklabh. Can you help me set it up? There's no proper documentation anywhere. 
PS: Currently running into an error related to firebase.

**Comment by Gaurav-Krishna-Gaali** [comment]
Thank you. I booked a slot. 👍
