### ISSUE TITLE
Issues api (Value for argument \"value\" is not a valid query constraint)

### ISSUE THREAD

**Issue by killbond007** [polkassembly/polkassembly#683]
Hello Polkassembly ，I've found an api bug. 
ex: 
curl --location 'https://api.polkassembly.io/api/v1/listing/off-chain-posts?listingLimit=10&proposalType=referendums_v2&page=4' \
--header 'x-network: polkadot' \
--data ''

error : {"error":"Value for argument \"value\" is not a valid query constraint. Cannot use \"undefined\" as a Firestore value (found in field \"`0`\"). If you want to ignore undefined values, enable `ignoreUndefinedProperties`."}%

**Comment by rajdeep7Singh** [comment]
Hey @killbond007 thanks for reaching out. Please don' t use `proposalType: referendums_v2` in this api as it is meant to fetch only offchain posts. There is a separate api for on chain posts present in the documentation. We will fix the documentation and throw more meaningful errors. Thanks
